name: Upload release assets

on:
  push:
    #branches:
      #- master
    tags:
      - 'v*'
  #release:
    #types: [released]
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag"
        required: true

jobs:
  upload-release-assets:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          lfs: 'true'

      - name: Upload FINISHED CSV and GeoPackage files as release assets
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: 'FINISHED/geopackages/*;FINISHED/*.csv'
          tags: true
          draft: false
