name: Upload release assets

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag"
        required: true

jobs:
  upload-release-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Check disk space before
        run: df -h

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Check disk space after
        run: df -h

      - name: Checkout earthquake-scenarios repository
        uses: actions/checkout@v3
        with:
          lfs: 'true'

      - name: Upload FINISHED CSV and GeoPackage files as release assets
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: 'FINISHED/geopackages/*;FINISHED/*.csv'
          tag_name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.release_tag || '' }}
          tags: true
          draft: false
